/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.java.gradle.project;

public class App {
    public String getGreeting() {
        return "Hello World! How are you!!!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
