name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      EdgeRuntime:
        description: 'Name of the Edge Runtime'
        required: true
        type: string
jobs:

  build:

    runs-on: ubuntu-windows-runner

    steps:
    - uses: actions/checkout@v3
    - name: Docker Containers
      run: docker ps
    - name: Docker Container Stop
      run: docker stop ${{ inputs.EdgeRuntime }}
    - name: Docker Containers after STOP
      run: docker ps
    - name: Docker Container Start
      run: docker start ${{ inputs.EdgeRuntime }}
    - name: Docker Containers after START
      run: docker ps
      # notify Microsoft Teams channel with a custom message
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
        title: This is from GitHub Actions - Edge Runtime - ${{ inputs.EdgeRuntime }} - stopped and started.
        summary: This is a message summary
