name: Container-Stop-Start-Sequential

on:
  workflow_dispatch:

  workflow_run:

    workflows: ["Microsoft-Teams-notification-Sequential"]

    types:

      - completed
jobs:

  ERT_STOP_START:

    runs-on: ubuntu-windows-runner

    steps:
    - uses: madhead/read-java-properties@latest
      id: all
      with:
        file: ./app/src/main/resources/edgeruntime.properties
        all: true
    - run: echo ${{ steps.all.outputs.EDGE_RUNTIME_LIST }} # ERT names from a property file
  
    - name: Mendax Loop through numbers
      id: loop
      run: |
          for etrStr in ${{ fromJson(steps.all.outputs.EDGE_RUNTIME_LIST) }}
          do
             - uses: actions/checkout@v3
             - name: Docker Containers
               run: docker ps
             - name: Docker Container Stop
               run: docker stop $etrStr
             - name: Docker Containers after STOP
               run: docker ps
             - name: Docker Container Start
               run: docker start $etrStr
             - name: Docker Containers after START
               run: docker ps
               # notify Microsoft Teams channel with a custom message
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
        title: This is from GitHub Actions - Edge Runtime - $etrStr - stopped and started.
        summary: This is a message summary
          done
