name: Container-Stop-Start-Sequential
on:
  workflow_dispatch:

  workflow_run:

    workflows: ["Microsoft-Teams-notification-Sequential"]

    types:

      - completed
jobs:
  ERT_STOP_START:
    runs-on: ubuntu-windows-runner
    steps:
    - uses: actions/checkout@v3
    - uses: madhead/read-java-properties@latest
      id: all
      with:
        file: ./app/src/main/resources/edgeruntime.properties
        all: true
    - run: echo ${{ steps.all.outputs.EDGE_RUNTIME_LIST }} # ERT names from a property file
  
    - name: Mendax Loop through numbers
      id: loop
      run: |
          for etrStr in ${{ steps.all.outputs.EDGE_RUNTIME_LIST }}
          do
          #echo "Mendax Current number: $etrStr"
          docker stop $etrStr
          docker ps
          docker start $etrStr
          docker ps
          done
  ERT_STOP_START-NOTIFICATION:
    runs-on: ubuntu-windows-runner
    needs: ERT_STOP_START
    steps:
    # notify Microsoft Teams channel with a custom message
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
        title: This is from GitHub Actions workflow "Edge Runtime Refresh Successfull"
        summary: This is a message summary 
