name: Container-Stop-Start-Sequential

on:
  workflow_dispatch:

  workflow_run:

    workflows: ["Microsoft-Teams-notification-Sequential"]

    types:

      - completed
jobs:

  build:

    runs-on: ubuntu-windows-runner

    steps:
    - uses: madhead/read-java-properties@latest
      id: all
      with:
        file: ./app/src/main/resources/edgeruntime.properties
        all: true

    - run: echo ${{ steps.all.outputs.EDGE-RUNTIME_LIST }} # Project's version from gradle.properties

    - uses: actions/checkout@v3
    - name: Docker Containers
      run: docker ps
    - name: Docker Container Stop
      run: docker stop ${{ steps.all.outputs.EDGE-RUNTIME_LIST }}
    - name: Docker Containers after STOP
      run: docker ps
    - name: Docker Container Start
      run: docker start ${{ steps.all.outputs.EDGE-RUNTIME_LIST }}
    - name: Docker Containers after START
      run: docker ps
      # notify Microsoft Teams channel with a custom message
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
        title: This is from GitHub Actions - Edge Runtime - ${{ steps.all.outputs.EDGE-RUNTIME_LIST }} - stopped and started.
        summary: This is a message summary
