name: Container-Stop-Start-Sequential
on:
  workflow_dispatch:

  workflow_run:

    workflows: ["Microsoft-Teams-notification-Sequential"]

    types:

      - completed
jobs:

  ERT_STOP_START:

    runs-on: ubuntu-windows-runner

    steps:
    - uses: actions/checkout@v3
    - uses: madhead/read-java-properties@latest
      id: all
      with:
        file: ./app/src/main/resources/edgeruntime.properties
        all: true
    - run: echo ${{ steps.all.outputs.EDGE_RUNTIME_LIST }} # ERT names from a property file
  
    - name: Mendax Loop through numbers
      id: loop
      run: |
          for etrStr in ${{ steps.all.outputs.EDGE_RUNTIME_LIST }}
          do
          #echo "Mendax Current number: $etrStr"
          docker stop $etrStr
          docker ps
          docker start $etrStr
          docker ps
          done
