name: Microsoft Teams notification
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-windows-runner
    steps:
    # notify on each build event like starting and finishing a build
    #- uses: toko-bifrost/ms-teams-deploy-card@master
     # if: always()
     # with:
     #   github-token: ${{ github.token }}
      #  webhook-uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
    # notify Microsoft Teams channel with a custom message
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
        title: This is from GitHub Actions "a custom message"
        summary: This is a message summary
